version: 0.2
cache:
  paths:
    - '/root/.npm/**/*'  # Cache npm dependencies
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - zip -r deploy1.zip src package.json appspec.yaml node_modules  # Use deploy1.zip as the name
  post_build:
    commands:
      - aws s3 cp deploy1.zip s3://artifact-buc-ash/deploy1.zip  # Use deploy1.zip here as well
artifacts:
  files:
    - deploy1.zip  # Update artifact name to deploy1.zip
