version: 0.2
cache:
  paths:
    - '/root/.npm/**/*'  # Cache npm dependencies
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - zip -r deployment.zip src package.json appspec.yaml node_modules
  post_build:
    commands:
      - aws s3 cp deployment.zip s3://artifact-buc-ash/deployment.zip
artifacts:
  files:
    - deployment.zip
