version: 0.2
cache:
  paths:
    - '/root/.npm/**/*'  # Cache npm dependencies
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - zip -r new-deployment.zip src package.json appspec.yaml node_modules  # Change zip name here
  post_build:
    commands:
      - aws s3 cp new-deployment.zip s3://artifact-buc-ash/new-deployment.zip  # Change zip name here as well
artifacts:
  files:
    - new-deployment.zip  # Update artifact name here as well
