version: 0.2
cache:
  paths:
    - '/root/.npm/**/*'  # Cache npm dependencies
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - zip -r deploy1.zip appspec.yaml src package.json node_modules  # Ensure appspec.yaml is included
  post_build:
    commands:
      - aws s3 cp deploy1.zip s3://artifact-buc-ash/deploy1.zip  # Upload deploy1.zip to S3
artifacts:
  files:
    - deploy1.zip
    - appspec.yaml  # Ensure appspec.yaml is explicitly included
    - src/**  # Include all source files
    - package.json
    - node_modules/**  # Ensure all dependencies are included
